# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               GT
tagline:             'Random Posts'
description:         'Thoughts and Notes'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Gaurav Tewari
  url:               
  email:             gaurav.recursive@gmail.com

# Custom vars
version:             1.0.0
